[tools]
"http:pencil" = { version = "latest", url = "https://www.pencil.dev/download/Pencil-linux-x64.tar.gz" }
node = "25.9.0"

[tasks.install]
run = "npm install"

[tasks.dev]
run = "npm run storybook"